import { memo } from "react";
import { Link } from "react-router-dom";
import useData from "../lib/useData.js";
import RichText from "./RichText.jsx";

// The agentic daily briefing: a short, cited, model-written summary of the window,
// generated by worker/pipeline/briefing.mjs and read from digests/briefing_<h>.json.
// The body is rendered by RichText, so on top of its inline [n] citation markers it
// now also auto-links any glossary term it mentions to that concept's hub, the same
// deep meshed linking the authored knowledge base uses. Concepts the briefing
// explicitly cites still appear as Reads On chips. Renders nothing until the artifact
// exists and has content, so a missing briefing never breaks the dashboard.
function Briefing({ horizon }) {
  const { data } = useData(`/data/digests/briefing_${horizon}.json`);
  if (!data || !data.headline || (data.severity ?? 0) < 1) return null;
  const sev = Math.max(1, Math.min(3, data.severity || 1));
  const items = Array.isArray(data.cited_items) ? data.cited_items : [];
  const concepts = Array.isArray(data.cited_concepts) ? data.cited_concepts : [];

  // Number the [n] markers in reading order and resolve each to its source item, the
  // worldthought citation pattern. RichText renders the markers from this map.
  const order = [];
  String(data.body || "").replace(/\[(\d+)\]/g, (_, d) => {
    if (!order.includes(d)) order.push(d);
    return _;
  });
  const citeMap = new Map();
  order.forEach((d, i) => {
    const item = items.find((it) => String(it.n) === d);
    if (item) citeMap.set(d, { num: i + 1, url: item.url, title: item.title });
  });

  const SEV_LABEL = { 2: "Notable", 3: "Significant" };
  return (
    <section className="card briefing" data-sev={sev} aria-label="Daily briefing">
      <div className="briefing-head">
        <span className="eyebrow">Briefing</span>
        {SEV_LABEL[sev] && <span className="briefing-sev">{SEV_LABEL[sev]}</span>}
        {/* The page dateline carries the single freshness stamp (the corpus
            snapshot date). The briefing is cached on a window-state hash, so its
            own generated date can drift a day from the digest; showing it here
            put two different dates in one view. Freshness lives in the dateline. */}
      </div>
      <p className="briefing-headline">{data.headline}</p>
      {data.body && <RichText as="p" className="briefing-body" text={data.body} citeMap={citeMap} withCitations />}
      {concepts.length > 0 && (
        <div className="briefing-reads">
          <span className="eyebrow">Reads On</span>
          <div className="chips">
            {concepts.map((c) => (
              <Link key={c.slug} to={`/technique/${c.slug}`} className="chip">{c.label}</Link>
            ))}
          </div>
        </div>
      )}
    </section>
  );
}

export default memo(Briefing);
