import { memo } from "react";
import { Link } from "react-router-dom";
import useData from "../lib/useData.js";

// The agentic daily briefing: a short, cited, model-written summary of the window,
// generated by worker/pipeline/briefing.mjs and read from digests/briefing_<h>.json.
// The body carries inline [n] markers that reference the new items the briefing drew
// on; render each as a numbered superscript link (numbered in reading order), the
// worldthought citation pattern. Concepts the briefing discusses become hub links
// (the Citation Contract). Renders nothing until the artifact exists and has content,
// so a missing briefing never breaks the dashboard.
function renderBody(body, citedItems) {
  const text = String(body || "");
  const order = [];
  text.replace(/\[(\d+)\]/g, (_, d) => {
    if (!order.includes(d)) order.push(d);
    return _;
  });
  const map = new Map();
  order.forEach((d, i) => {
    const item = citedItems.find((it) => String(it.n) === d);
    if (item) map.set(d, { num: i + 1, url: item.url, title: item.title });
  });
  return text.split(/(\[\d+\])/g).map((part, idx) => {
    const m = part.match(/^\[(\d+)\]$/);
    if (!m) return part;
    const ref = map.get(m[1]);
    if (!ref) return null;
    return (
      <sup key={idx} className="cite">
        <a href={ref.url} target="_blank" rel="noreferrer" title={ref.title}>{ref.num}</a>
      </sup>
    );
  });
}

const SEV_LABEL = { 2: "Notable", 3: "Significant" };

function Briefing({ horizon }) {
  const { data } = useData(`/data/digests/briefing_${horizon}.json`);
  if (!data || !data.headline || (data.severity ?? 0) < 1) return null;
  const sev = Math.max(1, Math.min(3, data.severity || 1));
  const items = Array.isArray(data.cited_items) ? data.cited_items : [];
  const concepts = Array.isArray(data.cited_concepts) ? data.cited_concepts : [];

  return (
    <section className="card briefing" data-sev={sev} aria-label="Daily briefing">
      <div className="briefing-head">
        <span className="eyebrow">Briefing</span>
        {SEV_LABEL[sev] && <span className="briefing-sev">{SEV_LABEL[sev]}</span>}
        {data.generated && <span className="faint mono" style={{ marginLeft: "auto" }}>{data.generated}</span>}
      </div>
      <p className="briefing-headline">{data.headline}</p>
      {data.body && <p className="briefing-body">{renderBody(data.body, items)}</p>}
      {concepts.length > 0 && (
        <div className="briefing-reads">
          <span className="eyebrow">Reads On</span>
          <div className="chips">
            {concepts.map((c) => (
              <Link key={c.slug} to={`/technique/${c.slug}`} className="chip">{c.label}</Link>
            ))}
          </div>
        </div>
      )}
    </section>
  );
}

export default memo(Briefing);
