import { memo } from "react";
import { Link } from "react-router-dom";
import useData from "../lib/useData.js";
import RichText from "./RichText.jsx";

// The agentic Watch-cycle digest: a short, cited, model-written paraphrase of the most
// salient information across the latest educator videos this cycle, generated by
// worker/pipeline/watch_digest.mjs and read from digests/watch.json. It complements the
// 6-hour ingestion and only refreshes when the latest videos change. Mirrors Briefing.jsx:
// the body renders via RichText (inline [n] citation markers plus glossary auto-linking),
// and the cited concepts appear as Reads On chips. Renders nothing until the artifact has
// content, so a missing or quiet digest never breaks the Watch page.
function WatchDigest() {
  const { data } = useData("/data/digests/watch.json");
  if (!data || !data.headline) return null;
  const items = Array.isArray(data.cited_items) ? data.cited_items : [];
  const concepts = Array.isArray(data.cited_concepts) ? data.cited_concepts : [];

  // Number the [n] markers in reading order and resolve each to its source video, the
  // worldthought citation pattern RichText renders from.
  const order = [];
  String(data.body || "").replace(/\[(\d+)\]/g, (_, d) => {
    if (!order.includes(d)) order.push(d);
    return _;
  });
  const citeMap = new Map();
  order.forEach((d, i) => {
    const item = items.find((it) => String(it.n) === d);
    if (item) citeMap.set(d, { num: i + 1, url: item.url, title: item.title });
  });

  return (
    <section className="card briefing" aria-label="What the educators are covering this cycle">
      <div className="briefing-head">
        <span className="eyebrow">This Cycle in Video</span>
      </div>
      <p className="briefing-headline">{data.headline}</p>
      {data.body && <RichText as="p" className="briefing-body" text={data.body} citeMap={citeMap} withCitations />}
      {concepts.length > 0 && (
        <div className="briefing-reads">
          <span className="eyebrow">Reads On</span>
          <div className="chips">
            {concepts.map((c) => (
              <Link key={c.slug} to={`/technique/${c.slug}`} className="chip">{c.label}</Link>
            ))}
          </div>
        </div>
      )}
    </section>
  );
}

export default memo(WatchDigest);
