import { readFileSync, writeFileSync, readdirSync, statSync, mkdirSync, existsSync, copyFileSync } from "node:fs";
import { resolve, dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

/*
  Glossary figure GENERATION (the AI-image half of the figure pipeline).

  The open-license image hunt (scripts/glossary_images.mjs search|wiki) filled every
  concept it could from Wikimedia Commons and the other open providers; what remains on
  docs/glossary_image_wishlist.md is the abstract or arXiv-locked tail that has no clean
  redistributable figure. Per the plain-labeling policy recorded in docs/GLOSSARY.md, the
  project fills that tail with figures it generates itself, cited honestly as machine-made.

  This script is ONLY the generator. The committed oracle scripts/glossary_images.mjs
  finalize remains the gate: it validates real image bytes, a redistributable license
  (licenseOk now accepts the "AI-generated" token), and authored alt before a row ships.
  A row is a claim; a validated file on disk is the evidence.

  Flow (generation is decoupled from acceptance on purpose, so a wrong diagram never
  ships unreviewed; an AI generator gets technical diagrams subtly wrong and a wrong
  teaching figure is worse than none):

    1. gen [--category <folder> | <slug>...] [--limit N] [--quality low|medium|high] [--size WxH] [--force]
         Resolve gap concepts (those with no row in content/glossary/images.json), build a
         house-style prompt from each concept's authored title + summary, call gpt-image-1,
         and write the image to the gitignored preview dir .tmp_imggen/<slug>.<ext> plus a
         metadata row in .tmp_imggen/_manifest.json. Idempotent: an already-generated
         preview is skipped unless --force, so a re-run never re-bills OpenAI. Output is WebP
         (output_compression 82) by default: these flat editorial illustrations are visually
         lossless at that setting but roughly a tenth the bytes of the raw PNG, which matters
         because every figure is committed to git history and shipped on every Netlify build.

    2. (main thread) Read each preview PNG and judge it: legible, on-concept, no garbled
         text or watermark. Author an honest alt (describes the image) and a teaching
         caption (teaches the concept) for each ACCEPTED slug into an accepted JSON file,
         e.g. {"q-learning": {"alt": "...", "caption": "..."}}.

    3. promote <accepted.json>
         For each accepted slug, copy .tmp_imggen/<slug>.png into public/images/glossary/
         and write a fully-attributed staging row into content/glossary/_img_stage/aigen.json
         (license "AI-generated", credit "Generated by OpenAI gpt-image-1, <date>", provider
         "OpenAI", license_url the model's usage terms). Rejected slugs simply never appear
         in the accepted file.

    4. node scripts/glossary_images.mjs finalize   (validates + bakes into images.json)
       node scripts/build_glossary.mjs             (regenerates the served artifacts)
*/

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "..");
const CONTENT = resolve(ROOT, "content/glossary");
const IMAGES_JSON = resolve(CONTENT, "images.json");
const PREVIEW = resolve(ROOT, ".tmp_imggen");
const MANIFEST = join(PREVIEW, "_manifest.json");
const OUT_DIR = resolve(ROOT, "public/images/glossary");
const STAGE_DIR = resolve(CONTENT, "_img_stage");
const STAGE_FILE = join(STAGE_DIR, "aigen.json");

const MODEL = "gpt-image-1";
// AI-generated figures carry no canonical license deed; license_url points at the
// generator's usage terms so the attribution chip links somewhere honest.
const TERMS_URL = "https://openai.com/policies/usage-policies/";
// WebP keeps these flat illustrations small (a tenth of the raw PNG) with no visible loss;
// the figure pad never needs transparency, so an opaque white background is fine.
const OUTPUT_FORMAT = "webp";
const OUTPUT_COMPRESSION = 82;
const EXT = OUTPUT_FORMAT === "jpeg" ? "jpg" : OUTPUT_FORMAT;

// House style baked into every prompt so the 200-odd generated figures read as one
// designed set, not a pile of random AI art, and sit cleanly on the white figure pad.
// The hard rule is "almost no text": gpt-image-1 still garbles dense diagram labels, and
// for a teaching figure where exactness is not load-bearing a clean wordless metaphor
// beats a mislabeled schematic.
const STYLE = [
  "Style: modern, minimal, editorial concept illustration; clean flat vector look with subtle depth;",
  "generous whitespace on a near-white (#f7f8fa) background; a restrained palette of deep indigo and slate blue",
  "with a single warm amber accent; calm, intelligent, textbook-quality.",
  "No photorealism, no 3D product render, no busy clutter, no UI screenshots.",
  "Critically: include NO sentences or paragraphs of text and NO garbled lettering;",
  "use at most two or three short real-word labels and only when they truly clarify, otherwise none.",
  "No watermark, no signature, no caption bar, no border.",
].join(" ");

const readJson = (p, fb) => {
  try {
    return JSON.parse(readFileSync(p, "utf8"));
  } catch {
    return fb;
  }
};

// Parse just the frontmatter of an authored entry (slug, title, summary, category).
function readFrontmatter(raw) {
  const text = String(raw).replace(/^﻿/, "");
  if (!text.startsWith("---")) return null;
  const end = text.indexOf("\n---", 3);
  if (end < 0) return null;
  const meta = {};
  for (const line of text.slice(3, end).split("\n")) {
    const i = line.indexOf(":");
    if (i > 0) meta[line.slice(0, i).trim()] = line.slice(i + 1).trim();
  }
  return meta;
}

// All gap concepts (no row in images.json yet), keyed by slug, with title/summary/folder.
function loadGaps() {
  const have = new Set(Object.keys(readJson(IMAGES_JSON, {})));
  const gaps = new Map();
  for (const folder of readdirSync(CONTENT)) {
    const dir = join(CONTENT, folder);
    let st;
    try {
      st = statSync(dir);
    } catch {
      continue;
    }
    if (!st.isDirectory()) continue;
    for (const f of readdirSync(dir)) {
      if (!f.endsWith(".md") || f.toLowerCase() === "readme.md") continue;
      const meta = readFrontmatter(readFileSync(join(dir, f), "utf8"));
      if (!meta?.slug || have.has(meta.slug)) continue;
      gaps.set(meta.slug, {
        slug: meta.slug,
        title: meta.title || meta.slug,
        summary: meta.summary || "",
        folder,
      });
    }
  }
  return gaps;
}

export function buildPrompt(title, summary, hint) {
  return [
    `Create one educational figure that teaches the concept "${title}" to a technically literate reader.`,
    summary,
    "Depict the core idea as a clear visual metaphor or simple schematic, favoring an honest conceptual",
    "illustration over a precise technical diagram (do not invent equations, axis numbers, or fake data).",
    // A per-concept steer, used on regeneration to fix a specific weakness in the first roll
    // (a muddled composition or garbled labels). Read from .tmp_imggen/_hints.json by slug.
    hint ? `Important for this figure: ${hint}` : "",
    STYLE,
  ].filter(Boolean).join(" ");
}

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

async function generateOne(prompt, { size, quality }) {
  const key = process.env.OPENAI_API_KEY;
  if (!key) throw new Error("OPENAI_API_KEY not set");
  let lastErr;
  for (let attempt = 0; attempt < 4; attempt += 1) {
    try {
      const r = await fetch("https://api.openai.com/v1/images/generations", {
        method: "POST",
        headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json" },
        body: JSON.stringify({
          model: MODEL,
          prompt,
          n: 1,
          size,
          quality,
          output_format: OUTPUT_FORMAT,
          output_compression: OUTPUT_COMPRESSION,
          background: "opaque",
          moderation: "low",
        }),
        signal: AbortSignal.timeout(180000),
      });
      if (r.status === 429 || r.status >= 500) throw new Error(`HTTP ${r.status}: ${(await r.text()).slice(0, 200)}`);
      if (!r.ok) {
        // 4xx other than 429 (e.g. a moderation block) is not worth retrying.
        const body = (await r.text()).slice(0, 300);
        const err = new Error(`HTTP ${r.status}: ${body}`);
        err.fatal = true;
        throw err;
      }
      const j = await r.json();
      const b64 = j.data?.[0]?.b64_json;
      if (!b64) throw new Error("no b64_json in response");
      return Buffer.from(b64, "base64");
    } catch (err) {
      lastErr = err;
      if (err.fatal || attempt === 3) break;
      await sleep(1500 * 2 ** attempt);
    }
  }
  throw lastErr;
}

// Resolve the worklist from flags: explicit slugs, or a whole category folder, else all gaps.
function resolveTargets(gaps, { category, slugs }) {
  if (slugs.length) {
    return slugs.map((s) => {
      const g = gaps.get(s);
      if (!g) throw new Error(`"${s}" is not a current gap (already has a figure, or not a durable slug)`);
      return g;
    });
  }
  let list = [...gaps.values()];
  if (category) list = list.filter((g) => g.folder === category);
  return list.sort((a, b) => a.slug.localeCompare(b.slug));
}

async function gen({ category, slugs, limit, quality, size, force, pool }) {
  mkdirSync(PREVIEW, { recursive: true });
  const gaps = loadGaps();
  let targets = resolveTargets(gaps, { category, slugs });
  if (limit) targets = targets.slice(0, limit);

  const manifest = readJson(MANIFEST, {});
  // Optional per-slug prompt steers for regeneration, keyed by slug.
  const hints = readJson(join(PREVIEW, "_hints.json"), {});
  const done = [];
  const failed = [];
  const skipped = [];

  // Bounded concurrency: keep a few in flight to cut wall-clock, but stay polite to the
  // image API's per-minute limit (external rate limit, respected; Anthropic-side pacing is not).
  const POOL = Math.max(1, pool || 3);
  let idx = 0;
  async function worker() {
    while (idx < targets.length) {
      const t = targets[idx];
      idx += 1;
      const file = join(PREVIEW, `${t.slug}.${EXT}`);
      if (existsSync(file) && !force) {
        skipped.push(t.slug);
        continue;
      }
      try {
        const prompt = buildPrompt(t.title, t.summary, hints[t.slug]);
        const buf = await generateOne(prompt, { size, quality });
        writeFileSync(file, buf);
        manifest[t.slug] = { title: t.title, summary: t.summary, folder: t.folder, size, quality, ext: EXT, kb: Math.round(buf.length / 1024) };
        writeFileSync(MANIFEST, `${JSON.stringify(manifest, null, 2)}\n`);
        done.push(`${t.slug} (${Math.round(buf.length / 1024)}kb)`);
        console.log(`  + ${t.slug} (${Math.round(buf.length / 1024)}kb)`);
      } catch (err) {
        failed.push(`${t.slug}: ${err.message}`);
        console.log(`  ! ${t.slug}: ${err.message}`);
      }
    }
  }
  console.log(`gen: ${targets.length} target(s), quality=${quality}, size=${size}, pool=${POOL}`);
  await Promise.all(Array.from({ length: Math.min(POOL, targets.length) }, () => worker()));
  console.log(`\ngen done: ${done.length} generated, ${skipped.length} skipped (cached), ${failed.length} failed`);
  if (skipped.length) console.log(`  skipped: ${skipped.join(", ")}`);
  if (failed.length) for (const f of failed) console.log(`  - ${f}`);
  console.log(`\nPreviews in ${PREVIEW}. Review them, then author an accepted.json and run: promote <accepted.json>`);
}

function isoDate() {
  // A normal Node process (not a Workflow sandbox), so the system clock is available.
  return new Date().toISOString().slice(0, 10);
}

function promote(acceptedPath) {
  const accepted = readJson(resolve(acceptedPath), null);
  if (!accepted || typeof accepted !== "object") throw new Error(`cannot read accepted file: ${acceptedPath}`);
  mkdirSync(OUT_DIR, { recursive: true });
  mkdirSync(STAGE_DIR, { recursive: true });
  const stage = readJson(STAGE_FILE, {});
  const manifest = readJson(MANIFEST, {});
  const date = isoDate();
  const promoted = [];
  const problems = [];
  for (const [slug, meta] of Object.entries(accepted)) {
    try {
      const ext = manifest[slug]?.ext || EXT;
      const src = join(PREVIEW, `${slug}.${ext}`);
      if (!existsSync(src)) throw new Error(`no preview ${ext.toUpperCase()} (run gen first)`);
      const alt = (meta.alt || "").trim();
      const caption = (meta.caption || "").trim();
      if (!alt) throw new Error("missing alt (required by finalize)");
      copyFileSync(src, join(OUT_DIR, `${slug}.${ext}`));
      stage[slug] = {
        file: `${slug}.${ext}`,
        alt,
        caption,
        credit: `Generated by OpenAI ${MODEL}, ${date}`,
        license: "AI-generated",
        license_url: TERMS_URL,
        source: "",
        provider: "OpenAI",
      };
      promoted.push(slug);
    } catch (err) {
      problems.push(`${slug}: ${err.message}`);
    }
  }
  writeFileSync(STAGE_FILE, `${JSON.stringify(stage, null, 2)}\n`);
  console.log(`promote: staged ${promoted.length} row(s) into ${STAGE_FILE}`);
  for (const p of promoted) console.log(`  + ${p}`);
  if (problems.length) {
    console.log(`promote: ${problems.length} problem(s)`);
    for (const p of problems) console.log(`  - ${p}`);
  }
  console.log(`\nNext: node scripts/glossary_images.mjs finalize  &&  node scripts/build_glossary.mjs`);
}

async function main() {
  const [cmd, ...rest] = process.argv.slice(2);
  const flags = {};
  const positional = [];
  for (let i = 0; i < rest.length; i += 1) {
    if (rest[i].startsWith("--")) {
      const name = rest[i].slice(2);
      const next = rest[i + 1];
      if (next !== undefined && !next.startsWith("--")) {
        flags[name] = next;
        i += 1;
      } else {
        flags[name] = true;
      }
    } else {
      positional.push(rest[i]);
    }
  }
  const flag = (n, d) => (flags[n] !== undefined ? flags[n] : d);

  if (cmd === "gen") {
    await gen({
      category: flag("category", null),
      slugs: positional,
      limit: flags.limit ? Number(flags.limit) : null,
      quality: String(flag("quality", "medium")),
      size: String(flag("size", "1024x1024")),
      force: flag("force", false) === true,
      pool: flags.pool ? Number(flags.pool) : 3,
    });
  } else if (cmd === "promote") {
    if (!positional[0]) throw new Error("usage: promote <accepted.json>");
    promote(positional[0]);
  } else if (cmd === "gaps") {
    const gaps = loadGaps();
    const byFolder = {};
    for (const g of gaps.values()) (byFolder[g.folder] ||= []).push(g.slug);
    for (const f of Object.keys(byFolder).sort()) console.log(`${f} (${byFolder[f].length}): ${byFolder[f].sort().join(", ")}`);
    console.log(`\nTotal gaps: ${gaps.size}`);
  } else {
    console.log("usage: glossary_generate_images.mjs <gen|promote|gaps> [...]");
    process.exitCode = 1;
  }
}

export { loadGaps, resolveTargets };

if (import.meta.url === pathToFileURL(process.argv[1] || "").href) {
  main().catch((e) => {
    console.error("glossary_generate_images failed:", e.message);
    process.exitCode = 1;
  });
}
